apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sujy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sujy
    app.kubernetes.io/part-of: ci1t-830-0017-app
  name: devfile-sample-sujy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sujy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sujy
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0017-tenant/ci1t-830-0017-app/devfile-sample-sujy@sha256:29125a0eed0e1e96f251901d5f80be75d43835db36e4fb6756168691d4ee25e4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
